server:
  port: 9085
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9085/eureka
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
