server:
  port: 9082
spring:
  jpa:
    show-sql: true
  application:
    name: order-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9085/eureka/
  instance:
    preferIpAddress: true
